### ISSUE TITLE
Dispatching of batches of emails

### ISSUE THREAD

**Issue by wanrick** [wanrick/bsword-notification#9]
How do we achieve this and how can the API help.

**Comment by MrDaubinet** [comment]
not sure if this is needed in our project as we only receive single users at a time

**Comment by eunicenkhammond** [comment]
Does this relate to the loop @MrDaubinet was spoke about earlier wrt sending batches of emails?

**Comment by SiyabongaMagubane** [comment]
We are adding this to our functionality
